# Generated by Django 4.0.4 on 2022-04-22 21:34

from pathlib import Path
import json

from django.db import migrations

from animal import models


PATH = Path(__file__).parent


def bulk_create(filepath, model):
    with open(filepath) as file:
        payload = json.load(file)

    instances = []
    for data in payload:
        obj = model()
        for key, value in data.items():
            setattr(obj, key, value)
        instances.append(obj)
    model.objects.bulk_create(instances)


def create_origem_animal(apps, schema_editor):
    bulk_create(PATH / "payloads/origem_animal.json", models.OrigemAnimal)


def create_motivo_resgate(apps, schema_editor):
    bulk_create(PATH / "payloads/motivo_resgate.json", models.MotivoResgate)


def create_especie_animal(apps, schema_editor):
    bulk_create(PATH / "payloads/especie_animal.json", models.EspecieAnimal)


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_origem_animal),
        migrations.RunPython(create_motivo_resgate),
        migrations.RunPython(create_especie_animal),
    ]
